appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LMPEpy4K+q4WgKvC/nroFwLGTz1ZuF81r2qbMsX1c/8HSZwlSOP3fwnQ3K990Ps0ApfF3lhf8RAl+0z9u+/PRiqgzFdk/8HDM1XMw16yphrKgFPN9XE70e0Oa6oMVzJIfJhCtIdk+dEHNI3cP/HsLx3JORyACkOKLr4AdQS5+vWICpgIVqxjNQ0A+ZtQpkPS1xMjZal/uUJWFDtL0+XXeaauIcEN44bK4cpgDGXA5Znl8jCkPha5170JMq3chuc5qpQNzUR0hqCf/s3/cHit/T6fZAFz33afvRy74ksZzteKwrXHKtjS1MUcFIOHnPVdq/liFYDYPsRk2LfQl2XPkzQoRyKFSi587U8lsqrOeRFMfdofW577BngLSFeyrOG7u6shPDmSHYBVsVnP6HiqTIXQSI9bjWbyvhCkH2vdf3YD/VNFqvqQVQYHlmbkbGx77Hs+aYT35XOHupTGgBExOF4YAwNuBURkAR3+y2830jLqCpBvoN3iOiOzuC5F0fEYw+VeV0q4EB5G0baXYBO6cbTju+0kDr8xoYuZavqUo4Z/lF1pQAJNYEfC9jjPKnGdWdIn+tZnsGoEa8gfdj+zBLJ6Rv9Gh2H591RAQadTjVsiYjug7LBCPHTFddfglVnFEKigT3bud0vjww+YIQ5enrz+bI4pdiQjenqri7QCdT4=}
